USE bolaku;
CREATE TABLE player_stats (
    id	INT,
    Player	VARCHAR(512),
    Position	VARCHAR(512),
    Club 	VARCHAR(512),
    Assist	VARCHAR(512),
    Goal	INT,
    Apps	INT,
    MinutesPlayed	INT
);

INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('1', 'Aaron Ramsdale', 'GK', 'Arsenal', '0', '0', '6', '540');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('2', 'David Raya', 'GK', 'Arsenal', '0', '0', '32', '2880');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('3', 'Bukayo Saka', 'Forward', 'Arsenal', '35', '16', '35', '2933');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('4', 'William SALiba', 'Defender', 'Arsenal', '1', '2', '38', '3420');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('5', 'Declan Rice', 'Midfield', 'Arsenal', '8', '7', '38', '3230');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('6', 'Martin Ødegaard', 'Midfield', 'Arsenal', '10', '8', '35', '3098');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('7', 'Gabriel Magalhaes', 'Defender', 'Arsenal', '0', '4', '36', '3044');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('8', 'Leandro Trossard ', 'Defender', 'Arsenal', '1', '12', '34', '1646');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('9', 'Kai Havertz', 'Forward', 'Arsenal', '7', '13', '37', '2639');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('10', 'Oleksandr Zinchenko', 'Defender', 'Arsenal', '2', '1', '27', '1722');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('11', 'Gabriel Jesus', 'Forward', 'Arsenal', '5', '4', '27', '1482');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('12', 'Takehiro Tomiyasu', 'Defender', 'Arsenal', '1', '2', '22', '1143');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('13', 'Eddie Nketiah', 'Forward', 'Arsenal', '2', '5', '27', '1073');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('14', 'Jakub Kiwior', 'Defender', 'Arsenal', '3', '1', '20', '945');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('15', 'Thomas Partey', 'Midfield', 'Arsenal', '0', '0', '14', '788');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('16', 'Jorginho', 'Midfield', 'Arsenal', '2', '0', '24', '919');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('17', 'Emile Smith Rowe', 'Midfield', 'Arsenal', '1', '0', '13', '346');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('18', 'Fabio Vieira', 'Midfield', 'Arsenal', '2', '1', '11', '292');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('19', 'Cedric Soares', 'Defender', 'Arsenal', '0', '0', '3', '59');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('20', 'Reis Nelson', 'Forward', 'Arsenal', '0', '0', '15', '257');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('21', 'Gabriel Martinelli', 'Forward', 'Arsenal', '4', '6', '35', '2029');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('22', 'Emiliano Martínez', 'GK', 'Aston Villa ', '0', '0', '34', '3015');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('23', 'Ollie Watkins', 'Forward', 'Aston Villa ', '5', '14', '37', '3328');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('24', 'Tyrone Mings', 'Defender', 'Aston Villa ', '0', '0', '1', '31');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('25', 'John McGinn', 'Midfield', 'Aston Villa ', '4', '6', '35', '3009');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('26', 'Leon Bailey', 'Forward', 'Aston Villa ', '9', '10', '35', '2072');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('27', 'Matty Cash', 'Defender', 'Aston Villa ', '2', '2', '29', '2142');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('28', 'Calum Chambers', 'Defender', 'Aston Villa ', '1', '0', '5', '159');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('29', 'Morgan Rogers', 'Forward', 'Aston Villa ', '1', '3', '11', '640');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('30', 'Moussa Diaby', 'Forward', 'Aston Villa ', '8', '6', '38', '2184');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('31', 'Lucas Digne', 'Defender', 'Aston Villa ', '3', '1', '33', '2410');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('32', 'Pau Torres', 'Defender', 'Aston Villa ', '0', '2', '29', '2463');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('33', 'Boubacar Kamara', 'Midfield', 'Aston Villa ', '1', '0', '20', '1659');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('34', 'Ezri Konsa', 'Defender', 'Aston Villa ', '0', '1', '35', '3073');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('35', 'Clément Lenglet', 'Defender', 'Aston Villa ', '1', '0', '14', '1155');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('36', 'Álex Moreno', 'Defender', 'Aston Villa ', '0', '2', '21', '1030');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('37', 'Robin Olsen', 'GK', 'Aston Villa ', '0', '0', '5', '405');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('38', 'Jacob Ramsey', 'Midfield', 'Aston Villa ', '1', '1', '16', '850');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('39', 'Nicolo Zaniolo', 'Forward', 'Aston Villa ', '0', '2', '21', '830');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('40', 'Douglas Luiz', 'Midfield', 'Aston Villa ', '5', '9', '35', '3001');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('41', 'Youri Tielemans', 'Midfield', 'Aston Villa ', '6', '2', '32', '1620');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('42', 'Ivan Toney', 'Forward', 'Brentford', '2', '7', '17', '1449');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('43', 'Bryan Mbeumo', 'Forward', 'Brentford', '6', '9', '25', '1959');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('44', 'Mathias Jensen', 'Midfield', 'Brentford', '3', '3', '32', '2217');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('45', 'Rico Henry', 'Defender', 'Brentford', '1', '0', '5', '402');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('46', 'Christian Nørgaard', 'Midfield', 'Brentford', '1', '2', '31', '2513');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('47', 'Kristoffer Ajer', 'Defender', 'Brentford', '1', '2', '28', '1833');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('48', 'Sergio Reguilon', 'Defender', 'Brentford', '4', '0', '16', '1122');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('49', 'Shandon Baptiste', 'Midfield', 'Brentford', '1', '1', '10', '224');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('50', 'Nathan Collins', 'Defender', 'Brentford', '1', '1', '32', '2649');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('51', 'Mikkel Damsgaard', 'Forward', 'Brentford', '2', '0', '23', '833');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('52', 'Josh Dasilva', 'Forward', 'Brentford', '0', '0', '3', '23');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('53', 'Frank Onyeka', 'Midfield', 'Brentford', '2', '1', '26', '1155');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('54', 'Mark Flekken', 'GK', 'Brentford', '1', '0', '37', '3285');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('55', 'Saman Ghoddos', 'Forward', 'Brentford', '0', '1', '19', '729');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('56', 'Kean Lewis-Potter', 'Forward', 'Brentford', '1', '3', '30', '1441');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('57', 'Ben Mee', 'Defender', 'Brentford', '0', '2', '16', '1276');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('58', 'Yoanne Wissa ', 'Forward', 'Brentford', '3', '12', '34', '2508');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('59', 'Ethan Pinnock', 'Defender', 'Brentford', '0', '2', '29', '2521');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('60', 'Kevin Schade', 'Forward', 'Brentford', '1', '2', '11', '331');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('61', 'Thomas Strakosha', 'GK', 'Brentford', '0', '0', '2', '135');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('62', 'Dominic Solanke', 'Forward', 'Bournemouth', '3', '19', '38', '3331');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('63', 'Philip Billing', 'Midfield', 'Bournemouth', '2', '2', '29', '1393');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('64', 'Neto', 'GK', 'Bournemouth', '0', '0', '32', '2880');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('65', 'Ryan Christie', 'Midfield', 'Bournemouth', '5', '0', '37', '2918');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('66', 'Lloyd Kelly', 'Defender', 'Bournemouth', '1', '0', '23', '1557');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('67', 'Max Aarons', 'Defender', 'Bournemouth', '1', '0', '20', '1234');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('68', 'Tyler Adams', 'Midfield', 'Bournemouth', '0', '0', '3', '118');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('69', 'Romain Faivre', 'Midfield', 'Bournemouth', '1', '5', '17', '37');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('70', 'Lewis Cook', 'Midfield', 'Bournemouth', '3', '0', '33', '2792');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('71', 'James Hill', 'Defender', 'Bournemouth', '3', '1', '18', '75');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('72', 'Milos Kerkez', 'Defender', 'Bournemouth', '1', '0', '28', '1975');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('73', 'Justin Kluivert', 'Forward', 'Bournemouth', '1', '7', '32', '1934');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('74', 'Chris Mepham', 'Forward', 'Bournemouth', '1', '0', '10', '613');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('75', 'Dango Ouattara', 'Forward', 'Bournemouth', '2', '1', '30', '1220');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('76', 'Alex Scott', 'Midfield', 'Bournemouth', '1', '1', '23', '1010');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('77', 'Illia Zabarni', 'Defender', 'Bournemouth', '0', '1', '37', '3330');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('78', 'Enes Unal', 'Forward', 'Bournemouth', '2', '2', '16', '320');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('79', 'Antoine Semenyo', 'Forward', 'Bournemouth', '2', '8', '33', '2111');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('80', 'Marcos Senesi', 'Defender', 'Bournemouth', '5', '4', '31', '2247');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('81', 'Luis Sinisterra', 'Forward', 'Bournemouth', '2', '2', '20', '692');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('82', 'Jason Steele', 'GK', 'Brighton', '0', '0', '17', '1530');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('83', 'Lewis Dunk', 'Defender', 'Brighton', '1', '3', '33', '2872');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('84', 'Tariq Lamptey', 'Defender', 'Brighton', '3', '0', '19', '912');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('85', 'Pervis Estupiñán', 'Defender', 'Brighton', '3', '2', '19', '1244');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('86', 'Jan Paul van Hecke', 'Defender', 'Brighton', '0', '0', '28', '2368');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('87', 'Solly March', 'Midfield', 'Brighton', '1', '3', '7', '558');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('88', 'Adam Lallana', 'Midfield', 'Brighton', '1', '0', '25', '846');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('89', 'Ansu Fati', 'Forward', 'Brighton', '0', '2', '19', '513');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('90', 'Pascal Groß', 'Midfield', 'Brighton', '10', '4', '36', '3114');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('91', 'Kaoru Mitoma', 'Forward', 'Brighton', '4', '3', '19', '1488');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('92', 'Evan Ferguson', 'Forward', 'Brighton', '0', '6', '27', '1365');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('93', 'Julio Enciso', 'Forward', 'Brighton', '2', '0', '12', '474');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('94', 'Danny Welbeck', 'Forward', 'Brighton', '1', '5', '29', '1703');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('95', 'Billy Gilmour', 'Midfield', 'Brighton', '1', '0', '30', '2125');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('96', 'Igor Julio', 'Defender', 'Brighton', '0', '0', '24', '1636');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('97', 'Carlos Baleba', 'Midfield', 'Brighton', '0', '0', '27', '1321');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('98', 'Joël Veltman', 'Defender', 'Brighton', '1', '1', '27', '1582');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('99', 'Ivan Ferguson', 'Forward', 'Brighton', '0', '6', '27', '1365');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('100', 'Simon Adingra', 'Forward', 'Brighton', '1', '6', '31', '2230');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('101', 'Facundo Buonanotte', 'Midfield', 'Brighton', '1', '3', '27', '1368');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('102', 'Arijanet Muric', 'GK', 'Burnley', '0', '0', '10', '900');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('103', 'Ameen Al Dakhil', 'Defender', 'Burnley', '0', '1', '13', '1055');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('104', 'Charlie Taylor', 'Defender', 'Burnley', '1', '1', '28', '2332');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('105', 'James Trafford', 'GK', 'Burnley', '0', '0', '28', '2520');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('106', 'Jordan Beyer', 'Defender', 'Burnley', '1', '0', '15', '1238');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('107', 'Josh Brownhill', 'Midfield', 'Burnley', '2', '4', '33', '2251');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('108', 'Jack Cork', 'Defender', 'Burnley', '0', '0', '4', '25');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('109', 'Jóhann Berg Guðmundsson', 'Defender', 'Burnley', '3', '1', '26', '1191');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('110', 'Manuel Benson', 'Forward', 'Burnley', '0', '0', '8', '110');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('111', 'Hannes Delcroix', 'Defender', 'Burnley', '0', '0', '12', '585');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('112', 'Jay Rodriguez', 'Forward', 'Burnley', '1', '2', '21', '813');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('113', 'Lyle Foster', 'Forward', 'Burnley', '3', '5', '24', '1906');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('114', 'Hjalmar Ekdal', 'Defender', 'Burnley', '0', '0', '8', '436');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('115', 'Vitinho', 'Defender', 'Burnley', '2', '0', '32', '2316');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('116', 'Luca Keleosho', 'Forward', 'Burnley', '1', '1', '15', '984');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('117', 'Dara O\'Shea', 'Defender', 'Burnley', '4', '3', '33', '2894');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('118', 'Nathan Redmond', 'Forward', 'Burnley', '0', '0', '12', '132');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('119', 'Zeki Amdouni', 'Forward', 'Burnley', '1', '5', '34', '1971');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('120', 'Sander Berge', 'Midfield', 'Burnley', '2', '1', '37', '3005');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('121', 'Mike Tresor', 'Forward', 'Burnley', '0', '0', '16', '414');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('122', 'Benoit Badiashile', 'Defender', 'Chelsea', '1', '0', '18', '1337');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('123', 'Thiago Silva', 'Defender', 'Chelsea', '1', '3', '31', '2527');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('124', 'Ben Chilwell', 'Defender', 'Chelsea', '1', '0', '13', '752');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('125', 'Reece James', 'Defender', 'Chelsea', '2', '0', '10', '421');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('126', 'Enzo Fernández', 'Midfield', 'Chelsea', '2', '3', '28', '2214');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('127', 'Conor Gallagher', 'Midfield', 'Chelsea', '7', '5', '37', '3135');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('128', 'Raheem Sterling', 'Forward', 'Chelsea', '4', '8', '31', '1981');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('129', 'Christopher Nkunku', 'Forward', 'Chelsea', '0', '3', '11', '438');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('130', 'Nicolas Jackson', 'Forward', 'Chelsea', '5', '14', '35', '2804');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('131', 'Levi Colwill', 'Defender', 'Chelsea', '1', '1', '23', '1798');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('132', 'Marc Cucurella', 'Defender', 'Chelsea', '2', '0', '21', '1784');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('133', 'Cole Palmer', 'Midfield', 'Chelsea', '11', '22', '33', '2614');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('134', 'Trevoh Chalobah', 'Defender', 'Chelsea', '0', '1', '13', '950');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('135', 'Noni Madueke', 'Forward', 'Chelsea', '2', '5', '23', '1053');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('136', 'Carney Chukwuemeka', 'Midfield', 'Chelsea', '1', '1', '9', '223');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('137', 'Romeo Lavia', 'Defender', 'Chelsea', '0', '0', '1', '32');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('138', 'Robert Sánchez', 'GK', 'Chelsea', '0', '0', '16', '1434');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('139', 'Malo Gusto', 'Defender', 'Chelsea', '6', '0', '27', '17755');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('140', 'Mykhailo Mudryk', 'Forward', 'Chelsea', '2', '5', '31', '1578');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('141', 'Djordje Petrovic', 'GK', 'Chelsea', '0', '0', '23', '1986');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('142', 'Remi Matthews ', 'GK', 'Crystal Palace', '0', '0', '1', '3');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('143', 'Sam Johnstone', 'GK', 'Crystal Palace', '0', '0', '20', '1797');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('144', 'Tyrick Mitchell', 'Defender', 'Crystal Palace', '3', '2', '37', '3208');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('145', 'Joachim Andersen', 'Defender', 'Crystal Palace', '3', '2', '38', '3416');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('146', 'Marc Guéhi', 'Defender', 'Crystal Palace', '1', '0', '25', '2022');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('147', 'Nathaniel Clyne', 'Defender', 'Crystal Palace', '0', '0', '19', '1337');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('148', 'Joel Ward', 'Defender', 'Crystal Palace', '1', '0', '26', '1982');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('149', 'Eberechi Eze', 'Forward', 'Crystal Palace', '4', '11', '27', '2065');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('150', 'Michael Olise', 'Forward', 'Crystal Palace', '6', '10', '19', '1227');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('151', 'Jeffrey Schlupp', 'Forward', 'Crystal Palace', '2', '2', '29', '1355');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('152', 'Cheick Doucouré', 'Midfield', 'Crystal Palace', '0', '0', '11', '921');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('153', 'David Ozoh', 'Defender', 'Crystal Palace', '0', '0', '9', '149');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('154', 'James Tomkins', 'Defender', 'Crystal Palace', '0', '0', '4', '8');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('155', 'Daniel Munoz', 'Defender', 'Crystal Palace', '4', '0', '16', '1439');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('156', 'Jordan Ayew', 'Forward', 'Crystal Palace', '7', '4', '35', '2549');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('157', 'Jean-Philippe Mateta', 'Forward', 'Crystal Palace', '5', '16', '35', '2283');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('158', 'Will Hughes', 'Midfield', 'Crystal Palace', '1', '0', '30', '1899');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('159', 'Chris Richards', 'Defender', 'Crystal Palace', '1', '1', '26', '2091');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('160', 'Jairo Riedewald', 'Midfield', 'Crystal Palace', '0', '0', '9', '229');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('161', 'Jesurun Rak-Sakyi', 'Forward', 'Crystal Palace', '0', '0', '6', '132');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('162', 'Jordan Pickford', 'GK', 'Everton', '0', '0', '38', '3420');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('163', 'Séamus Coleman', 'Defender', 'Everton', '0', '0', '12', '662');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('164', 'James Tarkowski', 'Defender', 'Everton', '1', '1', '38', '3419');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('165', 'Ben Godfrey', 'Defender', 'Everton', '0', '0', '15', '1122');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('166', 'Michael Keane', 'Defender', 'Everton', '0', '1', '9', '438');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('167', 'Vitalii Mykolenko', 'Defender', 'Everton', '0', '2', '28', '2471');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('168', 'Idrissa Gueye', 'Midfield', 'Everton', '0', '4', '25', '1892');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('169', 'Amadou Onana', 'Midfield', 'Everton', '0', '2', '30', '2090');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('170', 'Dwight McNeil', 'Forward', 'Everton', '6', '3', '35', '2897');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('171', 'Ashley Young', 'Defender', 'Everton', '0', '0', '31', '2288');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('172', 'Calvert-Lewin', 'Forward', 'Everton', '2', '7', '32', '2185');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('173', 'Youseff Chermiti', 'Forward', 'Everton', '0', '0', '18', '195');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('174', 'Lewis Dobbin', 'Forward', 'Everton', '0', '1', '12', '227');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('175', 'André Gomes', 'Midfield', 'Everton', '0', '1', '12', '503');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('176', 'Arnaut Danjuma', 'Forward', 'Everton', '0', '1', '14', '587');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('177', 'Nathan Patterson', 'Defender', 'Everton', '2', '0', '20', '999');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('178', 'Beto', 'Forward', 'Everton', '0', '3', '30', '939');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('179', 'James Garner', 'Midfield', 'Everton', '2', '1', '37', '3005');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('180', 'Jack Harrison', 'Forward', 'Everton', '3', '3', '29', '2219');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('181', 'Abdoulaye Doucouré', 'Midfield', 'Everton', '2', '7', '32', '2637');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('182', 'Bernd Leno', 'GK', 'Fulham', '0', '0', '38', '3420');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('183', 'Kenny Tete', 'Defender', 'Fulham', '0', '1', '14', '868');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('184', 'Issa Diop', 'Defender', 'Fulham', '0', '0', '18', '1425');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('185', 'Tim Ream', 'Defender', 'Fulham', '0', '1', '18', '1504');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('186', 'Antonee Robinson', 'Defender', 'Fulham', '6', '0', '37', '3270');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('187', 'João Palhinha', 'Midfield', 'Fulham', '1', '4', '33', '2709');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('188', 'Harrison Reed', 'Midfield', 'Fulham', '2', '0', '27', '1324');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('189', 'Andreas Pereira', 'Forward', 'Fulham', '7', '3', '37', '2637');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('190', 'Harry Wilson', 'Forward', 'Fulham', '6', '4', '35', '1614');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('191', 'Willian', 'Forward', 'Fulham', '2', '4', '31', '2054');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('192', 'Adama Traore', 'Forward', 'Fulham', '3', '2', '17', '364');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('193', 'Armando Broja', 'Forward', 'Fulham', '1', '0', '8', '82');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('194', 'Tom Cairney', 'Midfield', 'Fulham', '4', '1', '34', '1475');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('195', 'Sasa Lukic', 'Midfield', 'Fulham', '0', '1', '24', '1119');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('196', 'Fode Ballo-Toure', 'Defender', 'Fulham', '0', '0', '6', '65');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('197', 'Raul Jimenez', 'Forward', 'Fulham', '0', '7', '24', '1402');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('198', 'Bobby De  Cordova-Reid', 'Forward', 'Fulham', '2', '6', '33', '1424');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('199', 'Rodrigo Muniz', 'Forward', 'Fulham', '1', '9', '26', '1597');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('200', 'Tosin Adarabioyo', 'Defender', 'Fulham', '0', '2', '20', '1617');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('201', 'Alex Iwobi', 'Forward', 'Fulham', '2', '5', '30', '2202');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('202', 'Alisson Becker', 'GK', 'Liverpool', '0', '0', '28', '2520');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('203', 'Alexander-Arnold', 'Defender', 'Liverpool', '4', '3', '28', '2160');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('204', 'Virgil van Dijk', 'Defender', 'Liverpool', '2', '2', '36', '3178');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('205', 'Andy Robertson', 'Defender', 'Liverpool', '2', '3', '23', '1691');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('206', 'Ibrahima Konaté', 'Defender', 'Liverpool', '0', '0', '22', '1571');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('207', 'Ryan Gravenberch', 'Midfield', 'Liverpool', '0', '1', '26', '1121');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('208', 'Wataru Endo', 'Midfield', 'Liverpool', '0', '1', '29', '1719');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('209', 'Mohamed Salah', 'Forward', 'Liverpool', '10', '18', '32', '2535');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('210', 'Diogo Jota', 'Forward', 'Liverpool', '3', '10', '21', '1150');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('211', 'Luis Díaz', 'Forward', 'Liverpool', '5', '8', '37', '2646');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('212', 'Darwin Núñez', 'Forward', 'Liverpool', '8', '11', '36', '2046');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('213', 'Harvey Elliott', 'Midfield', 'Liverpool', '6', '3', '34', '1336');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('214', 'Curtis Jones', 'Midfield', 'Liverpool', '1', '1', '23', '1167');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('215', 'Jarell Quansah', 'Defender', 'Liverpool', '0', '2', '17', '1189');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('216', 'Kostas Tsimikas', 'Defender', 'Liverpool', '3', '0', '13', '677');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('217', 'Joël Matip', 'Defender', 'Liverpool', '0', '0', '10', '783');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('218', 'Cody Gakpo', 'Forward', 'Liverpool', '5', '8', '35', '1644');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('219', 'Stefan Bajčetić', 'Midfield', 'Liverpool', '0', '0', '1', '26');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('220', 'Alexis Mac Allister', 'Midfield', 'Liverpool', '5', '5', '33', '2609');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('221', 'Dominik Szobozlai', 'Midfield', 'Liverpool', '2', '3', '33', '2109');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('222', 'James Shea', 'GK', 'Luton Town', '0', '0', '1', '14');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('223', 'Tom Lockyer', 'Defender', 'Luton Town', '1', '1', '14', '1171');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('224', 'Andros Townsend', 'Midfield', 'Luton Town', '3', '1', '27', '1209');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('225', 'Reece Burke', 'Defender', 'Luton Town', '4', '0', '22', '1163');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('226', 'Amari\'i Bell', 'Defender', 'Luton Town', '0', '0', '21', '1722');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('227', 'Pelly-Ruddock Mpanzu', 'Midfield', 'Luton Town', '0', '0', '27', '1093');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('228', 'Marvelous Nakamba', 'Midfield', 'Luton Town', '0', '0', '13', '1134');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('229', 'Jordan Clark', 'Forward', 'Luton Town', '1', '1', '23', '1306');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('230', 'Elijah Adebayo', 'Forward', 'Luton Town', '0', '11', '27', '1418');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('231', 'Carlton Morris', 'Forward', 'Luton Town', '4', '11', '38', '2867');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('232', 'Cauley Woodrow', 'Forward', 'Luton Town', '1', '1', '24', '409');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('233', 'Gabriel Osho', 'Defender', 'Luton Town', '0', '2', '21', '1848');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('234', 'Luke Berry', 'Midfield', 'Luton Town', '1', '2', '17', '311');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('235', 'Ross Barkley', 'Midfield', 'Luton Town', '4', '5', '32', '2622');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('236', 'Issa Kabore', 'Defender', 'Luton Town', '2', '0', '24', '1732');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('237', 'Teden Mengi', 'Defender', 'Luton Town', '0', '1', '30', '2470');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('238', 'Chiedozie Ogbene', 'Forward', 'Luton Town', '1', '4', '30', '1993');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('239', 'Alfie Doughty', 'Forward', 'Luton Town', '8', '2', '37', '2937');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('240', 'Tahith Chong', 'Forward', 'Luton Town', '0', '4', '33', '1986');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('241', 'Thomas Kminski', 'GK', 'Luton Town', '0', '0', '38', '3406');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('242', 'Ederson', 'GK', 'Man City', '0', '0', '33', '2788');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('243', 'Kyle Walker', 'Defender', 'Man City', '4', '0', '32', '2767');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('244', 'Rúben Dias', 'Defender', 'Man City', '0', '0', '30', '2557');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('245', 'Nathan Aké', 'Defender', 'Man City', '2', '2', '29', '2044');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('246', 'Rodri', 'Midfield', 'Man City', '9', '8', '34', '2938');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('247', 'Kevin De Bruyne', 'Midfield', 'Man City', '10', '4', '18', '1227');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('248', 'Bernardo Silva', 'Forward', 'Man City', '9', '6', '33', '2581');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('249', 'Jack Grealish', 'Forward', 'Man City', '1', '3', '20', '1003');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('250', 'Phil Foden', 'Forward', 'Man City', '8', '19', '35', '2865');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('251', 'Erling Haaland', 'Forward', 'Man City', '5', '27', '31', '2556');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('252', 'Julián Álvarez', 'Forward', 'Man City', '9', '11', '36', '2657');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('253', 'John Stones', 'Defender', 'Man City', '0', '1', '16', '1064');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('254', 'Sergio Gómez', 'Defender', 'Man City', '1', '0', '6', '46');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('255', 'Stefan Ortega', 'GK', 'Man City', '0', '0', '9', '632');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('256', 'Manuel Akanji', 'Defender', 'Man City', '0', '2', '30', '2513');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('257', 'Jeremy Doku', 'Forward', 'Man City', '8', '3', '29', '1593');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('258', 'Diogo Dalot', 'Defender', 'Man United', '3', '2', '36', '3137');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('259', 'Raphaël Varane', 'Defender', 'Man United', '0', '1', '22', '1371');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('260', 'Lisandro Martínez', 'Defender', 'Man United', '1', '0', '11', '648');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('261', 'Luke Shaw', 'Defender', 'Man United', '0', '0', '12', '962');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('262', 'Casemiro', 'Midfield', 'Man United', '2', '1', '25', '1985');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('263', 'Christian Eriksen', 'Midfield', 'Man United', '2', '1', '22', '1339');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('264', 'Bruno Fernandes', 'Midfield', 'Man United', '8', '10', '35', '3119');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('265', 'Marcus Rashford', 'Forward', 'Man United', '2', '7', '33', '2278');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('266', 'Anthony Martial', 'Forward', 'Man United', '0', '1', '13', '445');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('267', 'Sofyan Amrabat', 'Defender', 'Man United', '0', '0', '21', '931');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('268', 'Antony', 'Forward', 'Man United', '1', '1', '29', '1323');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('269', 'Andre Onana', 'GK', 'Man United', '0', '0', '38', '3420');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('270', 'Scott McTominay', 'Midfield', 'Man United', '1', '7', '32', '1891');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('271', 'Johny Evans', 'Defender', 'Man United', '1', '0', '23', '1396');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('272', 'Harry Maguire', 'Defender', 'Man United', '2', '2', '22', '1650');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('273', 'Alejandro Garnacho', 'Forward', 'Man United', '4', '7', '36', '2573');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('274', 'Aaron Wan-Bissaka', 'Defender', 'Man United', '2', '0', '22', '1781');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('275', 'Kobbie Mainoo', 'Midfield', 'Man United', '1', '3', '24', '1939');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('276', 'Amad Diallo', 'Forward', 'Man United', '1', '1', '9', '388');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('277', 'Nick Pope', 'GK', 'Newcastle United', '0', '0', '15', '1346');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('278', 'Kieran Trippier', 'Defender', 'Newcastle United', '10', '1', '28', '2240');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('279', 'Fabian Schär', 'Defender', 'Newcastle United', '1', '4', '36', '3054');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('280', 'Sven Botman', 'Defender', 'Newcastle United', '2', '2', '17', '1378');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('281', 'Dan Burn', 'Defender', 'Newcastle United', '2', '2', '33', '2732');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('282', 'Bruno Guimarães', 'Midfield', 'Newcastle United', '8', '7', '37', '3268');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('283', 'Joelinton', 'Midfield', 'Newcastle United', '1', '2', '20', '1282');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('284', 'Miguel Almirón', 'Forward', 'Newcastle United', '1', '3', '33', '1945');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('285', 'Callum Wilson', 'Forward', 'Newcastle United', '1', '9', '20', '985');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('286', 'Alexander Isak', 'Forward', 'Newcastle United', '2', '21', '30', '2265');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('287', 'Joe Willock', 'Forward', 'Newcastle United', '0', '1', '9', '418');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('288', 'Sean Longstaff', 'Midfield', 'Newcastle United', '2', '6', '35', '2746');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('289', 'Sandro Tonalli', 'Midfield', 'Newcastle United', '0', '1', '8', '439');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('290', 'Jamaal Lascelles', 'Defender', 'Newcastle United', '0', '1', '16', '1080');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('291', 'Jacob Murphy', 'Forward', 'Newcastle United', '7', '3', '21', '1193');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('292', 'Emil Krafth', 'Defender', 'Newcastle United', '0', '0', '17', '910');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('293', 'Martin Dúbravka', 'GK', 'Newcastle United', '0', '0', '23', '1984');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('294', 'Anthony Gordon', 'Forward', 'Newcastle United', '10', '11', '35', '2898');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('295', 'Elliot Anderson', 'Midfield', 'Newcastle United', '2', '0', '21', '1022');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('296', 'Matz Sels', 'GK', 'Nottingham Forest', '0', '0', '16', '1440');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('297', 'Murillo', 'Defender', 'Nottingham Forest', '2', '0', '20', '2793');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('298', 'Anthony Elanga', 'Forward', 'Nottingham Forest', '9', '5', '36', '2434');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('299', 'Ryan Yates', 'Midfield', 'Nottingham Forest', '1', '1', '35', '1986');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('300', 'Callum Hudson-Odoi', 'Forward', 'Nottingham Forest', '1', '8', '29', '1854');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('301', 'Chris Wood', 'Forward', 'Nottingham Forest', '1', '14', '31', '1806');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('302', 'Ola Aina', 'Defender', 'Nottingham Forest', '1', '1', '22', '1700');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('303', 'Morgan Gibbs-White', 'Midfield', 'Nottingham Forest', '10', '5', '37', '3160');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('304', 'Neco Williams ', 'Defender', 'Nottingham Forest', '1', '0', '26', '1634');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('305', 'Matt Turner', 'GK', 'Nottingham Forest', '0', '0', '17', '1530');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('306', 'Nicolas Dominguez', 'Midfield', 'Nottingham Forest', '2', '2', '26', '1503');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('307', 'Moussa Niakhate', 'Defender', 'Nottingham Forest', '0', '1', '21', '1457');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('308', 'Harry Toffolo', 'Defender', 'Nottingham Forest', '3', '1', '23', '1455');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('309', 'Willy Boly', 'Defender', 'Nottingham Forest', '1', '2', '20', '1443');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('310', 'Andrew Omobamidele', 'Defender', 'Nottingham Forest', '0', '0', '11', '782');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('311', 'Divock Origi', 'Forward', 'Nottingham Forest', '1', '0', '20', '599');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('312', 'Nuno Tavarez', 'Defender', 'Nottingham Forest', '0', '0', '8', '455');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('313', 'Danilo', 'Midfield', 'Nottingham Forest', '2', '2', '29', '1796');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('314', 'Wes Foderingham', 'GK', 'Sheffield United', '0', '0', '30', '2648');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('315', 'George Baldock', 'Defender', 'Sheffield United', '1', '0', '13', '970');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('316', 'John Egan', 'Defender', 'Sheffield United', '0', '0', '6', '484');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('317', 'Jack Robinson', 'Defender', 'Sheffield United', '1', '1', '34', '2855');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('318', 'Anel Ahmedhodžić', 'Defender', 'Sheffield United', '0', '2', '31', '2649');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('319', 'Max Lowe', 'Defender', 'Sheffield United', '1', '0', '10', '500');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('320', 'James McAtee', 'Midfield', 'Sheffield United', '3', '3', '30', '1827');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('321', 'Oliver Norwood', 'Midfield', 'Sheffield United', '0', '1', '27', '1433');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('322', 'William Osula', 'Forward', 'Sheffield United', '0', '0', '21', '783');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('323', 'Ivo Grbic', 'GK', 'Sheffield United', '0', '0', '9', '772');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('324', 'Oli McBurnie', 'Forward', 'Sheffield United', '3', '6', '21', '1283');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('325', 'Rhian Brewster', 'Forward', 'Sheffield United', '0', '0', '13', '339');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('326', 'Ben Osborn', 'Midfield', 'Sheffield United', '2', '0', '224', '1359');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('327', 'Mason Holgate', 'Defender', 'Sheffield United', '0', '0', '10', '713');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('328', 'Auston Trusty', 'Defender', 'Sheffield United', '0', '0', '32', '2572');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('329', 'Jayden Bogle', 'Defender', 'Sheffield United', '0', '3', '34', '2792');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('330', 'Vinicius Souza', 'Midfield', 'Sheffield United', '0', '1', '36', '2672');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('331', 'Gustavo Hamer', 'Midfield', 'Sheffield United', '6', '4', '36', '2923');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('332', 'James McAtee', 'Midfield', 'Sheffield United', '3', '3', '30', '1827');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('333', 'Cristian Romero', 'Defender', 'Tottenham', '0', '5', '33', '2792');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('334', 'Ben Davies', 'Defender', 'Tottenham', '0', '1', '17', '1085');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('335', 'Timo Werner', 'Forward', 'Tottenham', '3', '2', '13', '814');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('336', 'Emerson Royal', 'Defender', 'Tottenham', '0', '1', '22', '1155');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('337', 'Højbjerg', 'Midfield', 'Tottenham', '0', '0', '36', '1293');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('338', 'Rodrigo Bentancur', 'Forward', 'Tottenham', '1', '1', '23', '1007');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('339', 'Yves Bissouma', 'Midfield', 'Tottenham', '0', '0', '28', '2081');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('340', 'Son Heung-min', 'Forward', 'Tottenham', '10', '17', '35', '2946');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('341', 'Dejan Kulusevski', 'Forward', 'Tottenham', '3', '8', '36', '2763');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('342', 'Richarlison', 'Forward', 'Tottenham', '4', '11', '28', '1492');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('343', 'Lo Celso', 'Midfield', 'Tottenham', '2', '2', '22', '495');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('344', 'Micky van de Ven', 'Defender', 'Tottenham', '0', '3', '27', '2342');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('345', 'James Maddison', 'Forward', 'Tottenham', '9', '4', '28', '2152');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('346', 'Pedro Poro', 'Defender', 'Tottenham', '7', '3', '35', '3092');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('347', 'Oliver Skipp', 'Midfield', 'Tottenham', '0', '0', '21', '694');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('348', 'Guiglielmo Vicario', 'GK', 'Tottenham', '0', '0', '38', '3420');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('349', 'Bryan Gil', 'Midfield', 'Tottenham', '0', '0', '11', '201');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('350', 'Destiny Udogie', 'Defender', 'Tottenham', '3', '2', '28', '2398');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('351', 'Łukasz Fabiański', 'GK', 'West Ham United', '0', '0', '10', '721');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('352', 'Vladimir Coufal', 'Defender', 'West Ham United', '7', '0', '36', '3136');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('353', 'Angelo Ogbonna', 'Defender', 'West Ham United', '0', '0', '11', '633');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('354', 'Kurt Zouma', 'Defender', 'West Ham United', '0', '3', '33', '2838');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('355', 'James Ward-Prowse', 'Midfield', 'West Ham United', '7', '7', '37', '3005');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('356', 'Tomáš Souček', 'Midfield', 'West Ham United', '2', '7', '37', '2874');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('357', 'Lucas Paquetá', 'Midfield', 'West Ham United', '6', '4', '31', '2634');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('358', 'Edson Alvarez', 'Midfield', 'West Ham United', '1', '1', '31', '2383');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('359', 'Michail Antonio', 'Forward', 'West Ham United', '2', '6', '26', '1710');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('360', 'Jarrod Bowen', 'Forward', 'West Ham United', '6', '16', '34', '3020');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('361', 'Emerson', 'Defender', 'West Ham United', '2', '1', '36', '3142');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('362', 'Alphonse Areola', 'GK', 'West Ham United', '0', '0', '31', '2699');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('363', 'Nayef Aguerd', 'Defender', 'West Ham United', '0', '1', '21', '1859');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('364', 'Ben Johnson', 'Defender', 'West Ham United', '0', '0', '14', '538');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('365', 'Kalvin Phillips', 'Midfield', 'West Ham United', '0', '0', '8', '307');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('366', 'Mohammed Kudus', 'Midfield', 'West Ham United', '6', '8', '33', '2483');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('367', 'Danny Ings', 'Forward', 'West Ham United', '0', '1', '20', '390');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('368', 'Maxwel Cornet', 'Forward', 'West Ham United', '0', '1', '7', '110');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('369', 'José Sá', 'GK', 'Wolverhampton', '1', '0', '35', '3038');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('370', 'Nelson Semedo', 'Defender', 'Wolverhampton', '1', '0', '36', '3092');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('371', 'Max Kilman', 'Defender', 'Wolverhampton', '0', '2', '38', '3420');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('372', 'Craig Dawson', 'Defender', 'Wolverhampton', '1', '1', '25', '2211');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('373', 'Rayan Aït-Nouri', 'Defender', 'Wolverhampton', '1', '2', '33', '2344');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('374', 'Matheus Cunha', 'Forward', 'Wolverhampton', '7', '12', '32', '2453');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('375', 'Matt Doherty', 'Defender', 'Wolverhampton', '0', '1', '30', '1142');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('376', 'Joao Gomes', 'Midfield', 'Wolverhampton', '1', '2', '34', '2658');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('377', 'Pablo Sarabia', 'Forward', 'Wolverhampton', '4', '7', '30', '1748');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('378', 'Hwang Hee-chan', 'Forward', 'Wolverhampton', '3', '12', '29', '2124');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('379', 'Santiago Bueno', 'Defender', 'Wolverhampton', '0', '0', '12', '820');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('380', 'Dan Dentley', 'GK', 'Wolverhampton', '0', '0', '5', '764');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('381', 'Toti Gomes', 'Defender', 'Wolverhampton', '3', '5', '35', '2744');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('382', 'Tommy Doyle', 'Midfield', 'Wolverhampton', '0', '0', '26', '1213');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('383', 'Mario Lemina', 'Midfield', 'Wolverhampton', '1', '4', '35', '2974');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('384', 'Boubacar Traore', 'Midfield', 'Wolverhampton', '0', '0', '24', '804');
INSERT INTO player_stats (id, Player, Position, Club , Assist, Goal, Apps, MinutesPlayed) VALUES ('385', 'Hugo Bueno', 'Defender', 'Wolverhampton', '0', '0', '22', '730');
